In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv("Iris.csv")
data.head(6)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [4]:
x = data.drop(['Id','Species',],axis=1)
y = data['Species']

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y)

In [6]:
from sklearn.model_selection import cross_val_score


In [7]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
cross_val_score(nb,x_train,y_train,cv=5).mean()

0.9462450592885375

In [8]:
from sklearn.svm import SVC
sv = SVC()
cross_val_score(sv,x_train,y_train,cv=5).mean()

0.9731225296442687

In [9]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
cross_val_score(dt,x_train,y_train,cv=5).mean()

0.9276679841897233

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
cross_val_score(knn,x_train,y_train,cv=5).mean()

0.9731225296442687

DecisionTreeClassifier and KNN is best

In [20]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [21]:
pred = dt.predict(x_test)
pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor'], dtype=object)

In [22]:
y_test

28         Iris-setosa
42         Iris-setosa
95     Iris-versicolor
89     Iris-versicolor
80     Iris-versicolor
3          Iris-setosa
144     Iris-virginica
27         Iris-setosa
132     Iris-virginica
93     Iris-versicolor
17         Iris-setosa
99     Iris-versicolor
100     Iris-virginica
22         Iris-setosa
106     Iris-virginica
88     Iris-versicolor
69     Iris-versicolor
85     Iris-versicolor
63     Iris-versicolor
7          Iris-setosa
15         Iris-setosa
58     Iris-versicolor
29         Iris-setosa
136     Iris-virginica
68     Iris-versicolor
30         Iris-setosa
130     Iris-virginica
138     Iris-virginica
102     Iris-virginica
128     Iris-virginica
72     Iris-versicolor
126     Iris-virginica
98     Iris-versicolor
122     Iris-virginica
86     Iris-versicolor
57     Iris-versicolor
4          Iris-setosa
54     Iris-versicolor
Name: Species, dtype: object

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.8947368421052632

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[11,  0,  0],
       [ 0, 15,  1],
       [ 0,  3,  8]], dtype=int64)

Test best Hyperparameter using GridSearchCV

In [25]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],'splitter':['best','random']}
grid_search = GridSearchCV(estimator=dt,param_grid=param_grid)
grid_search.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'splitter': ['best', 'random']})

In [26]:
grid_search.best_estimator_

DecisionTreeClassifier(criterion='log_loss', splitter='random')

In [27]:
grid_search.score(x_train,y_train)

1.0

In [28]:
model = DecisionTreeClassifier(criterion='log_loss',splitter='random')
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='log_loss', splitter='random')

In [35]:
pred=model.predict(x_test)
accuracy_score(y_test,pred)
confusion_matrix(y_test,pred)


array([[11,  0,  0],
       [ 0, 16,  0],
       [ 0,  3,  8]], dtype=int64)

Test KNN

In [38]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
kpred = knn.predict(x_test)

In [39]:
accuracy_score(y_test,kpred)

0.9210526315789473

In [40]:
confusion_matrix(y_test,kpred)

array([[11,  0,  0],
       [ 0, 14,  2],
       [ 0,  1, 10]], dtype=int64)